version: "2"
services:

  ############
  # FRONTEND #
  ############

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    links:
      - resque
    volumes:
      - run:/var/run
      - ./www:/var/www
      - ./build/nginx/sites:/etc/nginx/conf.d
      - ./build/nginx/nginx.conf:/etc/nginx/nginx.conf

  #########################################
  #             Cache and DB              #
  #########################################

  mysql:
    image: mysql
    volumes:
      - mysql-data:/var/lib/mysql
      - ./build/sqlmode.cnf:/etc/mysql/conf.d/sqlmode.cnf
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: picloud

  mongo:
    image: mongo:3.4
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"
    mem_limit: 2147483648

  redis:
    image: redis
    volumes:
      - redis-data:/data
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes

  ############
  #  PYTHON  #
  ############

  picloud:
    build:
      context: build/python
    image: promos/python:2
    links:
      - redis
      - mongo
      - mysql
    environment:
      APP_DEBUG: "true"
      REDIS_PORT_6379_TCP_ADDR: redis
      MYSQL_PORT_3306_TCP_ADDR: mysql
      MONGO_PORT_27017_TCP_ADDR: mongo
      MYSQL_PASSWORD: password
    volumes:
      - ./www/piCloud:/data
      - python-packages:/usr/local/lib/python2.7/site-packages
      - run:/var/run
    working_dir: /data
    entrypoint: sh
    command: -c "gunicorn manage:app -b unix:/var/run/picloud.sock -k gevent --worker-connections 1001 --workers=4 --pid /tmp/picloud.pid --reload"

  ################
  # Admin panels #
  ################

  resque:
    image: voycey/resque-web
    links:
      - redis
    command: -r redis://redis:6379 /resque-web.rb

volumes:
  mysql-data:
    driver: local
  mongo-data:
    driver: local
  redis-data:
    driver: local
  run:
    driver: local
  python-packages:
    driver: local
